# Generated by Django 6.0.4 on 2026-04-21 15:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUOTED', 'Quoted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('component_type', models.CharField(choices=[('NEW_PART', 'New Part'), ('REPAIR_SERVICE', 'Repair Service')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_alternative', models.ForeignKey(blank=True, help_text='Links a NEW_PART to its REPAIR_SERVICE counterpart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_part_for', to='services.component')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('item_type', models.CharField(choices=[('NEW', 'New'), ('REPAIR', 'Repair')], max_length=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_items', to='services.component')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.serviceorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='SIMULATED', max_length=20)),
                ('reference', models.CharField(default=None, max_length=50, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='services.serviceorder')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_contact', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_name'], name='services_ve_owner_n_f7e582_idx')],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='services.vehicle'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['component_type'], name='services_co_compone_f4bccf_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['is_active'], name='services_co_is_acti_6f3f05_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status'], name='services_se_status_d2293e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['created_at'], name='services_se_created_c72088_idx'),
        ),
    ]
